# Generated by Django 5.1.4 on 2025-01-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_task', models.TextField(default='', max_length=100)),
                ('created_date', models.DateTimeField(default='')),
            ],
        ),
    ]
