# Generated by Django 5.1.4 on 2025-01-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name_task',
            field=models.CharField(default='', max_length=100),
        ),
    ]
