# Generated by Django 5.1.4 on 2025-01-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_user_id_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_activer',
            field=models.BooleanField(default=True),
        ),
    ]
